---

name: Code Quality
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          exclude: "./.git/*"  # Optional.
          fail_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          pattern: "*.sh"  # Optional.
          reporter: github-pr-review  # Change reporter.
          shellcheck_flags: '--external-sources --format=gcc --shell=bash'

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: '.yamllint.yml'
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# FIXME: Add python linters?
